import { getDefaultConfig } from '@rainbow-me/rainbowkit';
import {
  mainnet, // Ethereum
  gnosis,
  base,
  arbitrum,
  optimism,
  avalanche,
  bsc,
  celo,
  polygon,
  mantle,
  zksync,
  ink,
  // Alphabetical order for remaining chains
  aurora,
  boba,
  cronos,
  filecoin,
  fraxtal,
  fuse,
  gravity,
  immutableZkEvm,
  linea,
  lisk,
  metis,
  mode,
  moonbeam,
  moonriver,
  polygonZkEvm,
  rootstock,
  scroll,
  sei,
  sepolia,
  sonic,
  soneium,
  taiko,
  unichain,
  worldchain,
} from 'wagmi/chains';

export const config = getDefaultConfig({
  appName: 'RainbowKit demo',
  projectId: 'YOUR_PROJECT_ID',
  chains: [
    // Primary chains in specified order
    mainnet, // Ethereum
    gnosis,
    base,
    arbitrum,
    optimism,
    avalanche,
    bsc,
    celo,
    polygon,
    mantle,
    zksync,
    ink,
    // Remaining chains in alphabetical order
    aurora,
    boba,
    cronos,
    filecoin,
    fraxtal,
    fuse,
    gravity,
    immutableZkEvm,
    linea,
    lisk,
    metis,
    mode,
    moonbeam,
    moonriver,
    polygonZkEvm,
    rootstock,
    scroll,
    sei,
    sonic,
    soneium,
    taiko,
    unichain,
    worldchain,
    // Testnets if enabled
    ...(process.env.NEXT_PUBLIC_ENABLE_TESTNETS === 'true' ? [sepolia] : []),
  ],
  ssr: false,
});
