name: Publish on dockerhub and quay.io
on:
  release:
    types: [published]
jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract tag
        id: get_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "TAG=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: |
            ethersphere/beeport-proxy:${{ steps.get_tag.outputs.TAG }}
            quay.io/ethersphere/beeport-proxy:${{ steps.get_tag.outputs.TAG }}

      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ethersphere/beeport-ui:${{ steps.get_tag.outputs.TAG }}
            quay.io/ethersphere/beeport-ui:${{ steps.get_tag.outputs.TAG }}
